In [ ]:
! pip install bert-for-sequence-classification==0.0.4

Collecting bert-for-sequence-classification==0.0.4
  Downloading bert_for_sequence_classification-0.0.4-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: transformers>=4.2.0 in /usr/local/lib/python3.11/dist-packages (from bert-for-sequence-classification==0.0.4) (4.52.3)
Requirement already satisfied: torch!=1.10,>=1.7.1 in /usr/local/lib/python3.11/dist-packages (from bert-for-sequence-classification==0.0.4) (2.6.0+cu124)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from bert-for-sequence-classification==0.0.4) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.11/dist-packages (from bert-for-sequence-classification==0.0.4) (2.2.2)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.11/dist-packages (from bert-for-sequence-classification==0.0.4) (1.6.1)
Requirement already satisfied: pyyaml>=6.0 in /usr/local/lib/python3.11/dist-packages (from bert-for-sequence-classification==0.0.4) (6.0.2)
Requirement already satisfied: openpyxl>=3.0.9 in /usr/local/lib/python3.11/dist-packages (from bert-for-sequence-classification==0.0.4) (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.11/dist-packages (from openpyxl>=3.0.9->bert-for-sequence-classification==0.0.4) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bert-for-sequence-classification==0.0.4) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bert-for-sequence-classification==0.0.4) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bert-for-sequence-classification==0.0.4) (2025.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0->bert-for-sequence-classification==0.0.4) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0->bert-for-sequence-classification==0.0.4) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0->bert-for-sequence-classification==0.0.4) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4) (4.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4) (1.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.2.0->bert-for-sequence-classification==0.0.4) (0.32.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.2.0->bert-for-sequence-classification==0.0.4) (24.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.2.0->bert-for-sequence-classification==0.0.4) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers>=4.2.0->bert-for-sequence-classification==0.0.4) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.2.0->bert-for-sequence-classification==0.0.4) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.2.0->bert-for-sequence-classification==0.0.4) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.2.0->bert-for-sequence-classification==0.0.4) (4.67.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers>=4.2.0->bert-for-sequence-classification==0.0.4) (1.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bert-for-sequence-classification==0.0.4) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch!=1.10,>=1.7.1->bert-for-sequence-classification==0.0.4) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers>=4.2.0->bert-for-sequence-classification==0.0.4) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers>=4.2.0->bert-for-sequence-classification==0.0.4) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers>=4.2.0->bert-for-sequence-classification==0.0.4) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers>=4.2.0->bert-for-sequence-classification==0.0.4) (2025.4.26)
Downloading bert_for_sequence_classification-0.0.4-py3-none-any.whl (14 kB)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.4 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 116.0 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 100.1 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 52.3 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.7 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 11.9 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 44.0 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 19.6 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 3.9 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 106.7 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, bert-for-sequence-classification
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed bert-for-sequence-classification-0.0.4 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

In [ ]:
import os
import pandas as pd
import torch
import torch.optim as optim
import torch.nn as nn
import json

from transformers import AutoModel, AutoTokenizer

from bert_clf import BertCLF, train_evaluate, predict_metrics, prepare_data_notebook, prepare_dataset
from bert_clf.utils import set_global_seed

In [ ]:
# Import necessary modules
from bert_clf.src.early_stopping import EarlyStopping
import numpy as np

# Monkey-patch the EarlyStopping class
def _init__(self, config):  # Rename __init__ to _init__ to avoid recursion
    self.patience = config['training']['patience']
    self.counter = 0
    self.best_score = None
    self.early_stop = False
    self.val_loss_min = np.inf  # Use np.inf instead of np.Inf
    self.delta = config['training']['delta']
    self.config = config

# Assign the modified _init__ method to the original __init__ attribute
EarlyStopping.__init__ = _init__

In [ ]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split



### Prepare UC-UNSC dataset

In [ ]:
df = pd.read_csv('sentence_CP.csv', sep =',')

In [ ]:
df

,Sentence_ID,Sentence,Arg_Type,Argument_IDs,Argument_Relations
0,1,"Once again, since the last briefing to the Cou...",claim,[1],{}
1,2,This is now the tenth time that the Council ha...,non-arg,[],{}
2,3,The General Assembly also took up the matter o...,non-arg,[],{}
3,4,"Following close to two weeks of relative calm,...",premise,[2],{}
4,5,The individuals involved called for secession ...,premise,[3],{}
...,...,...,...,...,...
4760,4761,We welcome Italy's decision to designate\ndial...,claim,[4556],{}
4761,4762,China supports practical and effective coopera...,claim,[4557],{}
4762,4763,We welcome all the positive efforts being made...,claim,[4558],{}
4763,4764,We hope that\nall the parties concerned will w...,claim,[4559],{}
4764,4765,The international\ncommunity should continue t...,claim,[4560],{}

In [ ]:
df['Label'] = df['Arg_Type'].apply(lambda x: 0 if x == 'non-arg' else 1)

In [ ]:
df['Label'].value_counts()

Label
1    4105
0     660
Name: count, dtype: int64

In [ ]:
df_train, df_temp = train_test_split(df, test_size=0.3, random_state=13)

df_val, df_test = train_test_split(df_temp, test_size=0.5, random_state=13)

In [ ]:
df_train

,Sentence_ID,Sentence,Arg_Type,Argument_IDs,Argument_Relations,Label
2016,2017,"""We control the border and\nwe will not let Uk...",premise,[1882],{},1
2832,2833,"By now, it is\nbarely making the world's headl...",premise,"[2676, 2677, 2678]","{(2676, 2678): 'support', (2676, 2677): 'suppo...",1
874,875,In order to implement the Geneva statement for...,claim,[823],{},1
4427,4428,We continue to be concerned about threats made...,premise,[4241],{},1
1313,1314,"Otherwise, the situation will further escalate...",premise,[1239],{},1
...,...,...,...,...,...,...
153,154,We call on all parties to exercise restraint a...,claim,[163],{},1
866,867,The onus is now on Russia to stop interfering ...,claim,[817],{},1
2790,2791,With the signing of the ceasefire in Minsk on\...,premise,[2636],{},1
74,75,Ukraine's Government has reached out repeatedl...,premise,[69],{},1
338,339,We once again call on our Russian partners to ...,claim,[353],{},1

In [ ]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
X = df["Sentence"].values
y = df["Label"].values

all_reports = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
    print(f"\n======== Fold {fold + 1} ========")

    df_train_fold = df.iloc[train_idx].reset_index(drop=True)
    df_val_fold = df.iloc[val_idx].reset_index(drop=True)

    # Set global seed per fold if needed
    set_global_seed(config['data']['random_state'])

    # Tokenizer and model must be re-initialized per fold
    tokenizer = AutoTokenizer.from_pretrained(config['transformer_model']["model"])
    model_bert = AutoModel.from_pretrained(config['transformer_model']["model"]).to(device)

    id2label, train_texts, valid_texts, train_targets, valid_targets = prepare_data_notebook(
        config=config,
        train_df=df_train_fold,
        test_df=df_val_fold
    )

    model = BertCLF(
        pretrained_model=model_bert,
        tokenizer=tokenizer,
        id2label=id2label,
        dropout=config['transformer_model']['dropout'],
        device=device
    ).to(device)

    optimizer = optim.Adam(model.parameters(), lr=config['transformer_model']['learning_rate'])
    criterion = nn.NLLLoss()

    training_generator, valid_generator = prepare_dataset(
        tokenizer=tokenizer,
        train_texts=train_texts,
        train_targets=train_targets,
        valid_texts=valid_texts,
        valid_targets=valid_targets,
        config=config
    )

    model = train_evaluate(
        model=model,
        training_generator=training_generator,
        valid_generator=valid_generator,
        criterion=criterion,
        optimizer=optimizer,
        num_epochs=config['training']['num_epochs'],
        average=config['training']['average_f1'],
        config=config
    )

    # Evaluate
    model.to('cpu')
    preds = [model.predict(sent) for sent in df_val_fold['Sentence']]
    report = classification_report(df_val_fold['Label'], preds, output_dict=True)
    all_reports.append(report)

# Optional: Aggregate metrics
import numpy as np
macro_f1s = [r['macro avg']['f1-score'] for r in all_reports]
print(f"\nAverage Macro F1 over 5 folds: {np.mean(macro_f1s):.3f}")

======== Fold 1 ========

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/bert_clf/src/pandas_dataset/SimpleDataFrame.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.train.dropna(inplace=True)

==== Epoch 1 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.36it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 32.03it/s]

Train F1: 0.47121984919475246
Eval F1: 0.5033966510175368

Train F1 micro: 0.7447698744769874
Eval F1 micro: 0.8616898148148148

Train F1 weighted: 0.7082870387601166
Eval F1 weighted: 0.799919660927889

==== Epoch 2 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:20<00:00, 11.93it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 32.10it/s]

Train F1: 0.6101048940718551
Eval F1: 0.7506074276038649

Train F1 micro: 0.8865062761506276
Eval F1 micro: 0.9179398148148148

Train F1 weighted: 0.8443042854762801
Eval F1 weighted: 0.9015317437278552

==== Epoch 3 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:20<00:00, 11.93it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 32.10it/s]

Train F1: 0.7570466420713022
Eval F1: 0.7647452345091913

Train F1 micro: 0.9160564853556485
Eval F1 micro: 0.9208333333333333

Train F1 weighted: 0.8998912326548136
Eval F1 weighted: 0.9068937539539274

==== Epoch 4 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:20<00:00, 11.94it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 31.88it/s]

Train F1: 0.789044840891068
Eval F1: 0.77870910853044

Train F1 micro: 0.9231171548117155
Eval F1 micro: 0.9197916666666667

Train F1 weighted: 0.9131382792119421
Eval F1 weighted: 0.9112010664149877

==== Epoch 5 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:20<00:00, 11.95it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 31.88it/s]

Train F1: 0.8077001854646978
Eval F1: 0.8058757269818191

Train F1 micro: 0.9343619246861925
Eval F1 micro: 0.9145833333333333

Train F1 weighted: 0.9262839528594382
Eval F1 weighted: 0.9104145525848142

==== Epoch 6 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:19<00:00, 11.96it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 32.04it/s]

Train F1: 0.8505955510395875
Eval F1: 0.7617865066103071

Train F1 micro: 0.9398535564853556
Eval F1 micro: 0.9179398148148148

Train F1 weighted: 0.9345672803289194
Eval F1 weighted: 0.9104370974660138

Computing final metrics...: 100%|██████████| 60/60 [00:01<00:00, 38.67it/s]

              precision    recall  f1-score   support

           0       0.76      0.60      0.67       132
           1       0.94      0.97      0.95       821

    accuracy                           0.92       953
   macro avg       0.85      0.78      0.81       953
weighted avg       0.91      0.92      0.91       953


======== Fold 2 ========

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/bert_clf/src/pandas_dataset/SimpleDataFrame.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.train.dropna(inplace=True)

==== Epoch 1 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.32it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 32.58it/s]

Train F1: 0.4597067501807329
Eval F1: 0.5341965222623469

Train F1 micro: 0.7332635983263598
Eval F1 micro: 0.8627314814814814

Train F1 weighted: 0.6998698214140946
Eval F1 weighted: 0.8018256655647058

==== Epoch 2 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.32it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 32.93it/s]

Train F1: 0.6702038809296667
Eval F1: 0.7428530255621004

Train F1 micro: 0.8967050209205021
Eval F1 micro: 0.9119212962962963

Train F1 weighted: 0.8671758457412836
Eval F1 weighted: 0.8969649217938985

==== Epoch 3 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.35it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 32.88it/s]

Train F1: 0.7755135434846667
Eval F1: 0.7949862558184849

Train F1 micro: 0.9202405857740585
Eval F1 micro: 0.91875

Train F1 weighted: 0.9075206936508535
Eval F1 weighted: 0.9080711113673604

==== Epoch 4 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.32it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 32.90it/s]

Train F1: 0.7941076128204035
Eval F1: 0.7640999347379249

Train F1 micro: 0.9293933054393305
Eval F1 micro: 0.9189814814814814

Train F1 weighted: 0.921730924872686
Eval F1 weighted: 0.9078328523099582

==== Epoch 5 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.29it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 32.52it/s]

Train F1: 0.8464331916230747
Eval F1: 0.7913888408233171

Train F1 micro: 0.94168410041841
Eval F1 micro: 0.915625

Train F1 weighted: 0.9360750041671002
Eval F1 weighted: 0.9083707477138888

==== Epoch 6 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.24it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 33.00it/s]

Train F1: 0.8756781151927469
Eval F1: 0.7511629414722706

Train F1 micro: 0.9526673640167364
Eval F1 micro: 0.9200231481481481

Train F1 weighted: 0.9495865105240129
Eval F1 weighted: 0.906101525140544

Computing final metrics...: 100%|██████████| 60/60 [00:01<00:00, 40.10it/s]

              precision    recall  f1-score   support

           0       0.84      0.52      0.64       132
           1       0.93      0.98      0.96       821

    accuracy                           0.92       953
   macro avg       0.88      0.75      0.80       953
weighted avg       0.92      0.92      0.91       953


======== Fold 3 ========

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/bert_clf/src/pandas_dataset/SimpleDataFrame.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.train.dropna(inplace=True)

==== Epoch 1 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.32it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 38.49it/s]

Train F1: 0.48892622674707525
Eval F1: 0.4795715480111214

Train F1 micro: 0.7437238493723849
Eval F1 micro: 0.8637731481481481

Train F1 weighted: 0.7096571383339844
Eval F1 weighted: 0.8036682066597495

==== Epoch 2 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.36it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 38.63it/s]

Train F1: 0.65371748309364
Eval F1: 0.7325945711548234

Train F1 micro: 0.891213389121339
Eval F1 micro: 0.91875

Train F1 weighted: 0.8575915828154815
Eval F1 weighted: 0.8947529615900722

==== Epoch 3 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.37it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 38.64it/s]

Train F1: 0.7682160529970732
Eval F1: 0.7837960020081862

Train F1 micro: 0.9168410041841004
Eval F1 micro: 0.928125

Train F1 weighted: 0.9028922591093865
Eval F1 weighted: 0.9138274318897637

==== Epoch 4 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:20<00:00, 11.39it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 38.62it/s]

Train F1: 0.7867971137380825
Eval F1: 0.8008148915276991

Train F1 micro: 0.9225941422594143
Eval F1 micro: 0.9273148148148148

Train F1 weighted: 0.910952072245227
Eval F1 weighted: 0.9187297265479699

==== Epoch 5 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.37it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 38.64it/s]

Train F1: 0.8241920275739675
Eval F1: 0.816207847625534

Train F1 micro: 0.9317468619246861
Eval F1 micro: 0.928587962962963

Train F1 weighted: 0.9248287604881383
Eval F1 weighted: 0.9164193491744939

==== Epoch 6 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:20<00:00, 11.39it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 38.68it/s]

Train F1: 0.8314080207059844
Eval F1: 0.8203687254795088

Train F1 micro: 0.9385460251046025
Eval F1 micro: 0.9302083333333333

Train F1 weighted: 0.9320914252477323
Eval F1 weighted: 0.9259692656683505

Computing final metrics...: 100%|██████████| 60/60 [00:01<00:00, 48.78it/s]

              precision    recall  f1-score   support

           0       0.81      0.64      0.72       132
           1       0.94      0.98      0.96       821

    accuracy                           0.93       953
   macro avg       0.88      0.81      0.84       953
weighted avg       0.93      0.93      0.93       953


======== Fold 4 ========

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/bert_clf/src/pandas_dataset/SimpleDataFrame.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.train.dropna(inplace=True)

==== Epoch 1 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.35it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 38.48it/s]

Train F1: 0.49669149893667147
Eval F1: 0.5365670966611008

Train F1 micro: 0.861663179916318
Eval F1 micro: 0.8616898148148148

Train F1 weighted: 0.8007252880759472
Eval F1 weighted: 0.8002454363074278

==== Epoch 2 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.37it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 38.77it/s]

Train F1: 0.6556094863925064
Eval F1: 0.7833363211697137

Train F1 micro: 0.8896443514644351
Eval F1 micro: 0.9273148148148148

Train F1 weighted: 0.8558203874951544
Eval F1 weighted: 0.917838426529818

==== Epoch 3 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.37it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 38.58it/s]

Train F1: 0.7765040557008631
Eval F1: 0.8274025037844096

Train F1 micro: 0.9163179916317992
Eval F1 micro: 0.9314814814814815

Train F1 weighted: 0.9034322064695118
Eval F1 weighted: 0.921873979575129

==== Epoch 4 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.31it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 38.61it/s]

Train F1: 0.8055602465334947
Eval F1: 0.8207051855393842

Train F1 micro: 0.9301778242677824
Eval F1 micro: 0.9356481481481481

Train F1 weighted: 0.9198068630560785
Eval F1 weighted: 0.9263340802424318

==== Epoch 5 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.35it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 38.38it/s]

Train F1: 0.8288594320720611
Eval F1: 0.817435960414152

Train F1 micro: 0.9359309623430963
Eval F1 micro: 0.9333333333333333

Train F1 weighted: 0.928561395282248
Eval F1 weighted: 0.9246728600738104

==== Epoch 6 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.34it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 38.59it/s]

Train F1: 0.8577601239801129
Eval F1: 0.8320683912135122

Train F1 micro: 0.9448221757322176
Eval F1 micro: 0.9346064814814814

Train F1 weighted: 0.9411602072917432
Eval F1 weighted: 0.9293216684071942

Computing final metrics...: 100%|██████████| 60/60 [00:01<00:00, 48.68it/s]

              precision    recall  f1-score   support

           0       0.84      0.66      0.74       132
           1       0.95      0.98      0.96       821

    accuracy                           0.93       953
   macro avg       0.89      0.82      0.85       953
weighted avg       0.93      0.93      0.93       953


======== Fold 5 ========

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/bert_clf/src/pandas_dataset/SimpleDataFrame.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.train.dropna(inplace=True)

==== Epoch 1 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.33it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 33.03it/s]

Train F1: 0.4797840265573045
Eval F1: 0.5207303350623814

Train F1 micro: 0.7502615062761506
Eval F1 micro: 0.8627314814814814

Train F1 weighted: 0.713468481382185
Eval F1 weighted: 0.8006689595048665

==== Epoch 2 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.36it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 32.83it/s]

Train F1: 0.6971894984739568
Eval F1: 0.6988963902931273

Train F1 micro: 0.9032426778242678
Eval F1 micro: 0.90625

Train F1 weighted: 0.8779233298421053
Eval F1 weighted: 0.8809625139010799

==== Epoch 3 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.36it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 32.88it/s]

Train F1: 0.7746669887844596
Eval F1: 0.7526038174277443

Train F1 micro: 0.917102510460251
Eval F1 micro: 0.9125

Train F1 weighted: 0.9051391297041177
Eval F1 weighted: 0.8985441569721526

==== Epoch 4 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:20<00:00, 11.38it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 32.88it/s]

Train F1: 0.8021950303895335
Eval F1: 0.7467600757500646

Train F1 micro: 0.9278242677824268
Eval F1 micro: 0.9127314814814814

Train F1 weighted: 0.9192814517302721
Eval F1 weighted: 0.8962521171528866

==== Epoch 5 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.37it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 32.93it/s]

Train F1: 0.8106155191109377
Eval F1: 0.740764456705747

Train F1 micro: 0.9375
Eval F1 micro: 0.8950231481481481

Train F1 weighted: 0.929405718187652
Eval F1 weighted: 0.8920744205487421

==== Epoch 6 out of 6 ====

Training loop: 100%|██████████| 239/239 [00:21<00:00, 11.37it/s]
Evaluating loop: 100%|██████████| 60/60 [00:01<00:00, 32.92it/s]

Train F1: 0.8404951317471545
Eval F1: 0.8112670258098511

Train F1 micro: 0.9424686192468619
Eval F1 micro: 0.9144675925925926

Train F1 weighted: 0.9367158111279078
Eval F1 weighted: 0.90270369039031

Computing final metrics...: 100%|██████████| 60/60 [00:01<00:00, 39.97it/s]

              precision    recall  f1-score   support

           0       0.80      0.53      0.64       132
           1       0.93      0.98      0.95       821

    accuracy                           0.92       953
   macro avg       0.87      0.75      0.80       953
weighted avg       0.91      0.92      0.91       953


Average Macro F1 over 5 folds: 0.819

In [ ]:
macro_f1s = [r['0']['f1-score'] for r in all_reports]
print(f"\nAverage F1 for 0 over 5 folds: {np.mean(macro_f1s):.3f}")

Average F1 for 0 over 5 folds: 0.682

In [ ]:
import numpy as np

# Example structure: list of classification reports as dicts, e.g. from sklearn.metrics.classification_report(output_dict=True)
# all_reports = [report_fold1, report_fold2, ..., report_foldN]
# Each report looks like:
# {
#   'class_0': {'precision': ..., 'recall': ..., 'f1-score': ..., 'support': ...},
#   'class_1': {...},
#   'accuracy': ...,
#   'macro avg': {'precision': ..., 'recall': ..., 'f1-score': ..., 'support': ...},
#   'weighted avg': {...},
# }

classes = ['1', '0']  # Replace with your actual class labels, e.g. ['Claim', 'Premise']

metrics = ['precision', 'recall', 'f1-score']

# Compute mean and std for each class and metric
for cls in classes:
    print(f"\nResults for {cls}:")
    for metric in metrics:
        scores = [report[cls][metric] for report in all_reports]
        mean = np.mean(scores)
        std = np.std(scores)
        print(f"  {metric.capitalize():<9}: {mean:.3f} ± {std:.3f}")

# Macro-average (all classes)
print(f"\nMacro-averaged results over {len(all_reports)} folds:")
for metric in metrics:
    scores = [report['macro avg'][metric] for report in all_reports]
    mean = np.mean(scores)
    std = np.std(scores)
    print(f"  {metric.capitalize():<9}: {mean:.3f} ± {std:.3f}")

# (Optional) Weighted-average
print(f"\nWeighted-averaged results over {len(all_reports)} folds:")
for metric in metrics:
    scores = [report['weighted avg'][metric] for report in all_reports]
    mean = np.mean(scores)
    std = np.std(scores)
    print(f"  {metric.capitalize():<9}: {mean:.3f} ± {std:.3f}")

Results for 1:
  Precision: 0.937 ± 0.008
  Recall   : 0.978 ± 0.005
  F1-score : 0.957 ± 0.004

Results for 0:
  Precision: 0.810 ± 0.029
  Recall   : 0.591 ± 0.056
  F1-score : 0.682 ± 0.039

Macro-averaged results over 5 folds:
  Precision: 0.874 ± 0.015
  Recall   : 0.784 ± 0.027
  F1-score : 0.819 ± 0.021

Weighted-averaged results over 5 folds:
  Precision: 0.919 ± 0.008
  Recall   : 0.924 ± 0.007
  F1-score : 0.919 ± 0.009

In [ ]:
macro_f1s = [r['0']['f1-score'] for r in all_reports]
print(f"\nAverage F1 for 0 over 5 folds: {np.mean(macro_f1s):.3f}")

Average F1 for 0 over 5 folds: 0.682

In [ ]:
import numpy as np

macro_f1s = [r['0']['f1-score'] for r in all_reports]
mean_f1 = np.mean(macro_f1s)
std_f1 = np.std(macro_f1s)

print(f"\nAverage F1 for class 0 over 5 folds: {mean_f1:.3f} ± {std_f1:.3f}")

Average F1 for class 0 over 5 folds: 0.682 ± 0.039

In [ ]:
macro_f1s = [r['1']['f1-score'] for r in all_reports]
mean_f1 = np.mean(macro_f1s)
std_f1 = np.std(macro_f1s)

print(f"\nAverage F1 for class 1 over 5 folds: {mean_f1:.3f} ± {std_f1:.3f}")

Average F1 for class 1 over 5 folds: 0.957 ± 0.004

In [ ]:
macro_f1s = [r['macro avg']['f1-score'] for r in all_reports]
mean_f1 = np.mean(macro_f1s)
std_f1 = np.std(macro_f1s)

print(f"\nAverage F1 for class 0 over 5 folds: {mean_f1:.3f} ± {std_f1:.3f}")

Average F1 for class 0 over 5 folds: 0.819 ± 0.021

In [ ]:
# prelim verdict -- seems that 6 epochs is fine here, make things better.

### Transformer Language Model

In [ ]:
config = dict(
    transformer_model = dict(
        model = "roberta-base",
        path_to_state_dict = False,
        device = 'cuda',
        dropout = 0.2,
        learning_rate = 2e-6,
        batch_size = 16,
        shuffle = True,
        maxlen = 128,
    ),
    data = dict(
        train_data_path = df_train,
        test_data_path = df_val,
        text_column = "Sentence",
        target_column = "Label",
        random_state = 20,
        test_size = 0.3,
        stratify=True
    ),
    training = dict (
    save_state_dict = False, # if False the model will be saved using torch.save(<model_class>)
        # and should be loaded like this: model = torch.load()
        # you will have to install the library to do so
    early_stopping = True,
    delta = 0.001,
    patience = 7,
    num_epochs = 6,
    average_f1 = 'macro',
    other_metrics = ['micro', 'weighted'],
    output_dir = "../results/",
    class_weight = True
    )
)

In [ ]:
set_global_seed(seed=config['data']['random_state'])
os.makedirs(config['training']['output_dir'], exist_ok=True)

In [ ]:
device = torch.device(config['transformer_model']['device'])
tokenizer = AutoTokenizer.from_pretrained(
        pretrained_model_name_or_path=config['transformer_model']["model"]
    )
model_bert = AutoModel.from_pretrained(
    pretrained_model_name_or_path=config['transformer_model']["model"]
).to(device)

#for param in model_bert.parameters():
    #param.requires_grad = False

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
id2label, train_texts, valid_texts, train_targets, valid_targets = prepare_data_notebook(
    config=config, train_df = df_train, test_df = df_val
)

/usr/local/lib/python3.11/dist-packages/bert_clf/src/pandas_dataset/SimpleDataFrame.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.train.dropna(inplace=True)

In [ ]:
model = BertCLF(
    pretrained_model=model_bert,
    tokenizer=tokenizer,
    id2label=id2label,
    dropout=config['transformer_model']['dropout'],
    device=device
    )

In [ ]:
model = model.to(device)

In [ ]:
optimizer = optim.Adam(model.parameters(), lr=float(config['transformer_model']['learning_rate']))
criterion = nn.NLLLoss()

training_generator, valid_generator = prepare_dataset(
    tokenizer=tokenizer,
    train_texts=train_texts,
    train_targets=train_targets,
    valid_texts=valid_texts,
    valid_targets=valid_targets,
    config=config
)

In [ ]:
# takes 2 min
model = train_evaluate(
    model=model,
    training_generator=training_generator,
    valid_generator=valid_generator,
    criterion=criterion,
    optimizer=optimizer,
    num_epochs=config['training']['num_epochs'],
    average=config['training']['average_f1'],
    config=config
)

==== Epoch 1 out of 2 ====

Training loop: 100%|██████████| 209/209 [01:07<00:00,  3.09it/s]
Evaluating loop: 100%|██████████| 45/45 [00:04<00:00, 10.86it/s]

Train F1: 0.47343500193576915
Eval F1: 0.48344998515311205

Train F1 micro: 0.7413277511961722
Eval F1 micro: 0.8597222222222223

Train F1 weighted: 0.7084617399153312
Eval F1 weighted: 0.7969889185826649

==== Epoch 2 out of 2 ====

Training loop: 100%|██████████| 209/209 [01:11<00:00,  2.93it/s]
Evaluating loop: 100%|██████████| 45/45 [00:04<00:00,  9.60it/s]

Train F1: 0.6623041117314694
Eval F1: 0.7278414309110145

Train F1 micro: 0.8892686261107314
Eval F1 micro: 0.9069444444444444

Train F1 weighted: 0.8572328221203434
Eval F1 weighted: 0.8797747500237304

Computing final metrics...: 100%|██████████| 45/45 [00:04<00:00, 10.58it/s]

              precision    recall  f1-score   support

           0       0.95      0.36      0.52       101
           1       0.90      1.00      0.95       614

    accuracy                           0.91       715
   macro avg       0.93      0.68      0.73       715
weighted avg       0.91      0.91      0.89       715

In [ ]:
model.to('cpu')

BertCLF(
  (pretrained_model): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): RobertaPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (drop): Dropout(p=0.2, inplace=False)
  (act): LogSoftmax(dim=1)
  (fc): Linear(in_features=768, out_features=2, bias=True)
)

In [ ]:
# takes 2-3 min.

preds = []
for i,j in zip(df_test['Sentence'], df_test['Label']):
    preds.append([model.predict(i), j, i])

In [ ]:
pred = []
for i in preds:
    pred.append(i[0])

true = []
for m in preds:
    true.append(m[1])

In [ ]:
# second
target_names = ['class 0', 'class 1']
print(classification_report(true, pred, target_names=target_names, digits=3))

              precision    recall  f1-score   support

     class 0      1.000     0.356     0.525        87
     class 1      0.918     1.000     0.957       628

    accuracy                          0.922       715
   macro avg      0.959     0.678     0.741       715
weighted avg      0.928     0.922     0.905       715

In [ ]:
# first
from sklearn.metrics import classification_report

target_names = ['class 0', 'class 1']
print(classification_report(true, pred, target_names=target_names, digits=3))

              precision    recall  f1-score   support

     class 0      0.575     0.548     0.561        84
     class 1      0.940     0.946     0.943       631

    accuracy                          0.899       715
   macro avg      0.758     0.747     0.752       715
weighted avg      0.897     0.899     0.898       715

In [ ]:
dummy = np.ones(715)

In [ ]:
# baseline for task 1 on UN-UNSC
target_names = ['class 0', 'class 1']
print(classification_report(true, dummy, target_names=target_names, digits=3))

              precision    recall  f1-score   support

     class 0      0.000     0.000     0.000        87
     class 1      0.878     1.000     0.935       628

    accuracy                          0.878       715
   macro avg      0.439     0.500     0.468       715
weighted avg      0.771     0.878     0.821       715

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))